Dear $username,

Welcome to MEOW TOWN!

I hope you enjoy your time here.

You can start by adding a file at /home/$username/public_html/index.html

This will be your homepage and you can view it at http://meow.town/~$username

If you like, you can introduce yourself to everyone by sending an email with:

    mail all

If you need anything, feel free to send me a mail by running this command:

    mail max

Thanks!

Your pal,
max
